### PR TITLE
Fix issue #19

### PR DESCRIPTION
**Pull request by sstone1**
This is a fix for https://github.com/IBM-Blockchain/learn-chaincode/issues/19

### CODE REVIEW

**Comment by mintzhao** [comment]
why no one merge this pull requests???

**Comment by trevorhiley** [comment]
This actually breaks when you deploy it to bluemix as bluemix seems to still have the older version of the dependency with the old interfaces.

**Comment by mintzhao** [comment]
@trevorhiley I just deploy successfully.

**Comment by bellaj** [comment]
this correction fix just the local build but when deployed to bluemix you will get an error

**Comment by dshuffma-ibm** [comment]
bellaj and trevorhiley are correct. we have a dilemma.  if we accept the change it will break deploying to a bluemix network since those use an older hyperledger version.  if we don't accept the change then it will break when deploying to a network using the latest hyperledger version.

we have a few options. 
- setup a new repo for learn chaincode that uses the latest shim
- create a folder for each version in this repo
- tag the current version, accept the changes, tag again and direct people to specific tags from the documentation
- wait for the bluemix networks to catch up and merge the change then

we are open to community feedback and any other ideas.

**Comment by dyancl** [comment]
@dshuffma-ibm, as a developer new to blockchain, I want to learn by deploying the code to a network - IBM chain, add transaction and eventually querying it (user story). The thing is, what we have in master will neither work with bluemix v0.5 blockchain or later version. 

I think the priority here is to update instructions so that new users can setup for v0.5.

**Comment by badrinathr** [comment]
Any reprieve here? This mismatch between bluemix and code.

**Comment by masterDev1985** [comment]
@sstone1 I've pushed some updates to this repo to support multiple fabric releases.  Could you check over the updates and close the pull request?

**Comment by dshuffma-ibm** [comment]
closing, we now have branches that work with [gopkg.in](http://gopkg.in/).

- [v1.0](https://github.com/ibm-blockchain/learn-chaincode/tree/v1.0)
    - Hyperledger fabric v0.5-developer-preview
- [v2.0](https://github.com/ibm-blockchain/learn-chaincode/tree/v2.0)
    - Hyperledger fabric v0.6-developer-preview

**Pull request closed without merging**
